### ISSUE TITLE
macOS Big Sur V11.4 Issue

### ISSUE THREAD

**Issue by NickC23** [colin-campbell/firestudio-catalina#11] opened 2021-08-04 22:40 UTC
Hi! Unfortunately my Mac ran an auto-update to the latest OS (11.4) which has seemed to break the patch/hack of the Presonus installer. Universal Control does still open without fail but does not recognize my device (FireStudio Mobile).  My interface is still getting power from the thunderbolt so not an issue on the connectivity front.  

I am running the Mid 2014 15" MacBook Pro with Retina.  Thank you so much for the hack and for taking a look at this.

**Comment by colin-campbell** [comment] 2021-08-06 19:38
@NickC23 if you have uninstalled and reinstalled, recommended you check your "System Preferences->Privacy & Security" page for information that looks like this.
![image](https://user-images.githubusercontent.com/1169963/128562981-a5f6f5f8-b51b-47ed-b3c0-7f2efb13798f.png)

After upgrading (to 11.5) I had to re-authorize certain  extensions:

![image](https://user-images.githubusercontent.com/1169963/128563059-8b866605-9c00-40e7-995b-da6247f81f5a.png)

Let me know how you get on.

**Comment by colin-campbell** [comment] 2023-01-02 19:29
Closing as confirmed working up to Ventura 13.1

**Closed as completed by colin-campbell** 2023-01-02 19:29 UTC
